version: "3"
services:
    proxy:
       build: ./haproxy
       command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg
       ports:
                - "${HA_PROXY_BIND_PORT}:${HA_PROXY_BIND_PORT}"
 
    wsgigateway:
        build: 
            context: ./uwsgi
            args:
                - WSGI_PORT=${WSGI_PORT}
        command: uwsgi --http :${WSGI_PORT} --wsgi-file run.py --callable app --master --processes 2
